- name: Variables list
  hosts: localhost
  vars:
    alphabets:
      - a
      - b
      - c

  tasks:
    - name: Echo index 0
      ansible.builtin.debug:
        msg: "{{ alphabets[0] }}"
    - name: Echo index 1
      ansible.builtin.debug:
        msg: "{{ alphabets[1] }}"
    - name: Echo index 2
      ansible.builtin.debug:
        msg: "{{ alphabets[2] }}"
