- name: Create users
  hosts: all

  vars:
    users_to_create:
      - name: bob
      - name: alice1
      - name: john

  tasks:
    - name: Create users
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
      with_items: "{{ users_to_create }}"
